version: 0.3.{build}

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: vs2012
    BACKEND: --with-sff --with-opengl --with-glfw --with-dx11
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: vs2015
    BACKEND: --with-sff --with-opengl --with-glfw --with-dx11 --with-sokol
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: vs2015
    BACKEND: --with-sff --with-bgfx
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLSET: vs2017
    BACKEND: --with-sff --with-opengl --with-glfw --with-dx11 --with-sokol
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLSET: vs2017
    BACKEND: --with-sff --with-bgfx

configuration:
  - Debug
  - Release

install:
  - git clone https://github.com/bkaradzic/bx ..\bx
  - ps: pushd ..\bx
  - git fetch origin 2ca39fce297bce94efb62e1c06eb2814f02b69d9
  - git reset --hard FETCH_HEAD
  - ps: popd
  
  - git clone https://github.com/bkaradzic/bimg ..\bimg
  - ps: pushd ..\bimg
  - git fetch origin 6afba8a0eb9333bf5777ab9ad0fea572e3557c74
  - git reset --hard FETCH_HEAD
  - ps: popd

  - git clone https://github.com/bkaradzic/bgfx ..\bgfx
  - ps: pushd ..\bgfx
  - git fetch origin 0f3f81aa05525ab350379ce8e34eb37c80b7aefe
  - git reset --hard FETCH_HEAD
  - ps: popd
  
  - git submodule update --init --recursive

  - ps: pushd scripts
  - ps: powershell [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN32.zip" -OutFile 'glfw-3.2.1.bin.WIN32.zip'
  - ps: powershell [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN64.zip" -OutFile 'glfw-3.2.1.bin.WIN64.zip'
  - ps: Expand-Archive 'glfw-3.2.1.bin.WIN32.zip' -DestinationPath '..\Externals\'
  - ps: Expand-Archive 'glfw-3.2.1.bin.WIN64.zip' -DestinationPath '..\Externals\'
  - ps: popd
  
  - cd scripts
  - ..\..\bx\tools\bin\windows\genie %BACKEND% %TOOLSET%

build:
  project: .projects/$(TOOLSET)/ImWindow.sln
  
after_build:
  - 7z a ImWindow.zip "%APPVEYOR_BUILD_FOLDER%\ImWindow.h" "%APPVEYOR_BUILD_FOLDER%\ImWindow.cpp" "%APPVEYOR_BUILD_FOLDER%\ImwConfig.h"

artifacts:
  - path: Output\*.exe
  - path: ImWindow.zip
